### ISSUE TITLE
Middleware component

### ISSUE THREAD

**Issue by dbonner1987** [chrisbjr/api-guard#59]
Hi,

Are there any plans to create a middleware component for the class instead of having to extend the controller? In a small project, albeit very different, we are dealing with requests that forward on to various other services that cannot be extended by the `ApiGuardController`. 

I would be willing to contribute this if you're happy to accept the feature?

Cheers

**Comment by chrisbjr** [comment]
Hi @dbonner1987 I've tried making this into a middleware at the start of Laravel 5.0 but experienced some limitations and couldn't achieve the functionality I wanted. However, since Laravel 5.1 now accepts middelware parameters, I can try again. I'll make another branch soon and any help would definitely be appreciated.

**Comment by dbonner1987** [comment]
Good stuff @chrisbjr, I'll keep an eye out for the branch. In the meantime I'll make a start on knocking it together for my needs.

Cheers

**Comment by awkwardusername** [comment]
Please see v3.0.0
