### ISSUE TITLE
Separate logging interface/package? Also, ideas about 3.0

### ISSUE THREAD

**Issue by awkwardusername** [chrisbjr/api-guard#61]
Well, it's a thought. It would be nice if api-guard does only one thing after all.

If @chrisbjr agrees, then we'd do `3.0`. Also thinking of making options about how we do auth, eg. JWT.

**Comment by skatcat31** [comment]
Actually I like that the API key logs the requests and can be turned off. It allows for a nice little bit of security. Currently I have it setup so that every midnight the table gets emptied of logs that are older than the last day, so if some high traffic is coming in I can easily see the IP address there instead of having to go into my nginx logs. It makes tracking down abusive IPs much easier and make deleting abusive accounts a synch. Yes rate limits are doable, but for the application model I'm working in, rate limits are impractical, so logging became a must have for us.

Of course there's always the option of rolling your own logging system per controller method, but setting that up for every application is a lot more annoying than just installing api keyguard and getting it in there too and turning it off if I don't need it for a method, or turning it off and turning it on for a method. Maybe instead of a new version without it, offer a fork of it without it? Otherwise the current version system get thrown a little wacky if you decide to offer both versions.

Another question is if github allows x.y.z version identifiers, in which case you can do 2.x.0 as no logging, 2.x.1 as logging, and then the minor version is the x. This could allow both flavors to be in the same repo, and compatible(assuming you put the missing table in)

**Comment by chrisbjr** [comment]
Thanks @skatcat31 we've made improvements in the authentication but also discussed with @awkwardusername that we won't be moving to JWT as this is a different use case. API keys is what this library is about.
